### ISSUE TITLE
Compiler Bug 5.2

### ISSUE THREAD

**Issue by Mobias97** [nohana/NohanaImagePicker#115]
Hey,

I get this Error:

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /xxxx/Carthage/Build/iOS/NohanaImagePicker.framework/Modules/NohanaImagePicker.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

Please help.

Btw ty for the Project!

**Comment by rizumi** [comment]
@Mobias97 
Hi

Probably the cause is different Swift version build with carthage and xcode project.
Please so retry `carthage update`.

If your have both Xcode11.4 and Xcode11.3.1 or other version, set the path Xcode11.4 using `xcode-select` before `carthage update`.

**Comment by Mobias97** [comment]
Ty, Carthage update helps me!
