### ISSUE TITLE
Version 0.6.1 Not available anymore

### ISSUE THREAD

**Issue by GioValentin** [nohana/NohanaImagePicker#69]
<img width="650" alt="tinygrab screen shot 1-17-17 3 03 51 pm" src="https://cloud.githubusercontent.com/assets/7150688/22037689/34b9b17a-dcc6-11e6-9dae-51cc5fe7fe71.png">

**Comment by haranicle** [comment]
Sorry, I stopped supporting pods.
Please use Carthage.

**Comment by richardszalay** [comment]
@haranicle Out of interest, why did you decide to stop supporting Cocoapods?
