### ISSUE TITLE
Selected Assest or color change

### ISSUE THREAD

**Issue by t2ac32** [nohana/NohanaImagePicker#85]
Is there any way to change the "selected" green asset to maybe another color like system blue or a selected asset in the Xcode assets library?

**Comment by haranicle** [comment]
@t2ac32 You can use `picker.config.image`.

```
let picker = NohanaImagePickerController()
picker.config.image.droppedSmall = UIImage(named: "your-image")
```

**Comment by t2ac32** [comment]
@haranicle it worked pretty straight forward. Thanks!

**Comment by haranicle** [comment]
👍
