### ISSUE TITLE
Ugly Animation on iPhoneX 💢

### ISSUE THREAD

**Issue by haranicle** [nohana/NohanaImagePicker#91]
![untitled](https://user-images.githubusercontent.com/5178877/31181480-6860403a-a95c-11e7-8990-115b7e893a10.gif)

**Comment by Noodlekim** [comment]
このイシューと関係あるかもしれません。
[Qiita](https://qiita.com/kazuhiro4949/items/db2cbcd5bc06c3e0009e)

**Comment by haranicle** [comment]
情報ありがとうございます。
この問題の原因はわかっていて、iOS11から追加された `Safe Area` という機能が関係しています。
なんとなく修正の仕方はわかっているのですが、手がつけられていません。申し訳ないです。

**Comment by Noodlekim** [comment]
@haranicle さんが行ってたどおりsafe areaのせいでした。
ありがとうございます。
一応、私の方で修正しておきました。
https://github.com/nohana/NohanaPhotoBookIos/pull/1715
