### ISSUE TITLE
Navigation Bar Language 

### ISSUE THREAD

**Issue by Coooi** [nohana/NohanaImagePicker#96]
Hi dev team,

Is there a way to change the navigation bar buttons text and also the bottom bar label text?
Specially for **Cancel**, **Done** buttons.

Cheers,
Marco

**Comment by haranicle** [comment]
Hi @Coooi 

You can change toolbar title with `picker.config`.

```
picker.config.strings.toolbarTitleNoLimit = "🐷 %ld"
picker.config.strings.toolbarTitleHasLimit = "🐷 %ld / %ld"
```

But, there is no way to change title of navigation bar buttons, because it is implemented with `UIBarButtonSystemItem`.

Ofcourse, you can change implementations and we welcome patches.

Thank you.

**Comment by Coooi** [comment]
Many thanks, @haranicle.
You may close this issue.
Cheers,
Marco

**Comment by haranicle** [comment]
Cheers, 😉
